DROP TABLE IF EXISTS USUARIOS;
CREATE TABLE USUARIOS (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR (50) NOT NULL,
    email VARCHAR (70) NOT NULL,
    telefono VARCHAR (15) ,
    edad INT
);